### ISSUE TITLE
What's the difference between blue and yellow block?

### ISSUE THREAD

**Issue by wil-low** [Another-Soul/NoxOS#1]
Shouldn't they differ by cost or imply some pattern rewards as the fill the progressbar?

**Comment by aroderg** [comment]
A blue segment gives you additional points upon level completion, yellow segments do not do so. Filling 100% of the progress bar with blue segment awards the player with (1000 * level) points, and the Perfectionist bonus (1200 points regardless of level). More blue segments in the progress bar give you more "Progress points" after the level. (50% of blue segments give you 50% of the points from the "Progress points" bonus, for example 2000 points on Level 4)

**Comment by wil-low** [comment]
I see, makes sense, thank you
